name: Deploy Node.js server to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # or your required version

      - name: Install dependencies
        run: |
          cd server
          npm ci

      # Optional: Run tests
      # - name: Run tests
      #   run: |
      #     cd server
      #     npm test

      # Optional: Build step if you have a build process
      # - name: Build
      #   run: |
      #     cd server
      #     npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: RDSPITAPP
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server
